### ISSUE TITLE
Upgrade Flutter to version 3.10.0 or higher

### ISSUE THREAD

**Issue by dongfengweixiao** [stagingrdkm/meta-rdk-flutter#2]
Can I upgrade Flutter to version 3.10.0 or higher? Thank you.

**Comment by dwrobel** [comment]
Yes, please.

Latest version `3.10.6` would be appreciated.

You can prepare it almost entirely on your forked repositories _(in your `conf/local.conf` just keep overrides to URL's which points to `LibertyGlobal`)_. Later on we could easily transfer all your newly created branches to us _(git SHAs will be preserved)_.
